name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make SSH directory
        run: mkdir -p $HOME/.ssh

      - name: Add SSH private key
        run: echo "${{ secrets.EC2_SSH_KEY }}" > $HOME/.ssh/id_rsa

      - name: Fix SSH key permissions
        run: chmod 600 $HOME/.ssh/id_rsa

      - name: Add EC2 host to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> $HOME/.ssh/known_hosts

      - name: Check SSH key size (debug)
        run: echo "Key size: $(echo "${{ secrets.EC2_SSH_KEY }}" | wc -c)"

      - name: Deploy backend to EC2
        run: |
          rsync -avz -e "ssh -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no" ./backend/ ${{ se_
